version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # updating this dependency has caused issues in the past, we should only touch this if there is an update for security purposes
      - dependency-name: "cloudevents"
      # updating this dependency has caused issues in the past, we should only touch this if there is an update for security purposes
      - dependency-name: "jsforce2"
      # due to the version of jsforce used, typescript complains loudly if the node types are bumped
      - dependency-name: "@types/node"
      # we're already at the highest version of the following that we can migrate to without introducing breaking changes to node 14 in the runtime
      - dependency-name: "@salesforce/core"
      # whatwg-mimetype 4.0.0 sets the minimum supported node version to 18 but we support all the way back to node 14 in the runtime
      - dependency-name: "whatwg-mimetype"
      # eslint and related plugins won't run on node 14 for these versions
      # - eslint: >8.x
      # - plugins:
      #   - @typescript-eslint/eslint-plugin: >5.x
      #   - @typescript-eslint/parser: >5.x
      - dependency-name: "eslint"
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      # chai hits a parsing issue on node 14 in versions >4.x
      - dependency-name: "chai"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
