---
version: 2.1

orbs:
  node: circleci/node@4.7
  win: circleci/windows@2.2.0

jobs:
  node-17: &test
    docker:
      - image: node:17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run format check
          command: npm run format:check
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run build
          command: npm run build
  node-16:
    <<: *test
    docker:
      - image: node:16
  node-14:
    <<: *test
    docker:
      - image: node:14
  windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: node info
          shell: powershell.exe
          command: |
            node --version
            npm --version
      - run:
          name: Install dependencies
          shell: powershell.exe
          command: npm ci
      - run:
          name: Run unit tests
          shell: powershell.exe
          command: npm run test

workflows:
  check-and-build:
    jobs:
      - node-17
      - node-16
      - node-14
      - windows
