version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  check-and-build:
    docker:
      # We need the JDK in order to run Wiremock.
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run format check
          command: npm run format:check
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run build
          command: npm run build

workflows:
  check-and-build:
    jobs:
      - check-and-build
